name: Between Bastion and Buttress
description: "Code, Cloud Computing, Community and Common Sense"
baseurl: https://blog.such.computer
github: rdodev
twitter: WallOfFire

markdown: kramdown
kramdown:
 input: GFM
highlighter: pygments
logo: false
paginate: 15
relative_permalinks: true
permalink: /posts/:title
excerpt_separator: "<!-- more -->"

# Details for the RSS feed generator
author: 'Ruben Orduz'
rss_post_limit: 5
url: rss.xml
