name: Don't Read This Blog
description: "Code, Cloud Computing, Community and Common Sense"
baseurl: /
github: rdodev
twitter: MassHaste

markdown: kramdown
kramdown:
 input: GFM
highlighter: rouge
logo: false
paginate: 15
permalink: posts/:title
excerpt_separator: "<!-- more -->"
year: 2017
# Details for the RSS feed generator
author: 'Ruben Orduz'

gems:
  - jekyll-paginate
  - jekyll-feed
