name: Between Bastion and Buttress
description: "Code, Cloud Computing, Community and Common Sense"
github: rdodev
twitter: WallOfFire

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
relative_permalinks: true
permalink: posts/:title
excerpt_separator: "<!-- more -->"

# Details for the RSS feed generator
url:            'blog.such.computer'
author:         'Ruben Orduz'
