name: Between Bastion and Buttress
description: "Code, Cloud Computing, Community and Common Sense"
meta_description:
github: rdodev
twitter: WallOfFire

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'rdodev.github.io'
author:         'Ruben Orduz'
