name: Between Bastion and Butress
description: "Code, Cloud Computing, Community and Common Sense"
meta_description:
github: rdodev
twitter: WallOfFire

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
